import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Shakib Nibir Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-light dark:bg-dark`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
